require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PomodorosController do

  # This should return the minimal set of attributes required to create a valid
  # Pomodoro. As you add validations to Pomodoro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "start_time" => "2013-05-14 10:43:11" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PomodorosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pomodoros as @pomodoros" do
      pomodoro = Pomodoro.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pomodoros).should eq([pomodoro])
    end
  end

  describe "GET show" do
    it "assigns the requested pomodoro as @pomodoro" do
      pomodoro = Pomodoro.create! valid_attributes
      get :show, {:id => pomodoro.to_param}, valid_session
      assigns(:pomodoro).should eq(pomodoro)
    end
  end

  describe "GET new" do
    it "assigns a new pomodoro as @pomodoro" do
      get :new, {}, valid_session
      assigns(:pomodoro).should be_a_new(Pomodoro)
    end
  end

  describe "GET edit" do
    it "assigns the requested pomodoro as @pomodoro" do
      pomodoro = Pomodoro.create! valid_attributes
      get :edit, {:id => pomodoro.to_param}, valid_session
      assigns(:pomodoro).should eq(pomodoro)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pomodoro" do
        expect {
          post :create, {:pomodoro => valid_attributes}, valid_session
        }.to change(Pomodoro, :count).by(1)
      end

      it "assigns a newly created pomodoro as @pomodoro" do
        post :create, {:pomodoro => valid_attributes}, valid_session
        assigns(:pomodoro).should be_a(Pomodoro)
        assigns(:pomodoro).should be_persisted
      end

      it "redirects to the created pomodoro" do
        post :create, {:pomodoro => valid_attributes}, valid_session
        response.should redirect_to(Pomodoro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pomodoro as @pomodoro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pomodoro.any_instance.stub(:save).and_return(false)
        post :create, {:pomodoro => { "start_time" => "invalid value" }}, valid_session
        assigns(:pomodoro).should be_a_new(Pomodoro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pomodoro.any_instance.stub(:save).and_return(false)
        post :create, {:pomodoro => { "start_time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pomodoro" do
        pomodoro = Pomodoro.create! valid_attributes
        # Assuming there are no other pomodoros in the database, this
        # specifies that the Pomodoro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pomodoro.any_instance.should_receive(:update_attributes).with({ "start_time" => "2013-05-14 10:43:11" })
        put :update, {:id => pomodoro.to_param, :pomodoro => { "start_time" => "2013-05-14 10:43:11" }}, valid_session
      end

      it "assigns the requested pomodoro as @pomodoro" do
        pomodoro = Pomodoro.create! valid_attributes
        put :update, {:id => pomodoro.to_param, :pomodoro => valid_attributes}, valid_session
        assigns(:pomodoro).should eq(pomodoro)
      end

      it "redirects to the pomodoro" do
        pomodoro = Pomodoro.create! valid_attributes
        put :update, {:id => pomodoro.to_param, :pomodoro => valid_attributes}, valid_session
        response.should redirect_to(pomodoro)
      end
    end

    describe "with invalid params" do
      it "assigns the pomodoro as @pomodoro" do
        pomodoro = Pomodoro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pomodoro.any_instance.stub(:save).and_return(false)
        put :update, {:id => pomodoro.to_param, :pomodoro => { "start_time" => "invalid value" }}, valid_session
        assigns(:pomodoro).should eq(pomodoro)
      end

      it "re-renders the 'edit' template" do
        pomodoro = Pomodoro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pomodoro.any_instance.stub(:save).and_return(false)
        put :update, {:id => pomodoro.to_param, :pomodoro => { "start_time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pomodoro" do
      pomodoro = Pomodoro.create! valid_attributes
      expect {
        delete :destroy, {:id => pomodoro.to_param}, valid_session
      }.to change(Pomodoro, :count).by(-1)
    end

    it "redirects to the pomodoros list" do
      pomodoro = Pomodoro.create! valid_attributes
      delete :destroy, {:id => pomodoro.to_param}, valid_session
      response.should redirect_to(pomodoros_url)
    end
  end

end
